### PR TITLE
custom css selector 'giftaid-value' added

### PR DESCRIPTION
**Pull request by Igor-Tkachenko**

### CODE REVIEW

**Review by codepuncher — COMMENTED** [review]
What is the purpose of this?

**Comment by Igor-Tkachenko** [comment]
Harry want to use not only "amount" input field as a source for giftaid value but other field types like "radio" or " dropdown"

**Comment by codepuncher** [comment]
I think it is better if you use the form total. Can you do that?

**Comment by Igor-Tkachenko** [comment]
Added form-total field to calculation

**Comment by Igor-Tkachenko** [comment]
@codepuncher could you take a look

**Review by codepuncher — APPROVED** [review]

**Comment by codepuncher** [comment]
How does this work?

**Comment by Igor-Tkachenko** [comment]
When form-total field added to the form its value is taken for calculation for gift-aid field.
If there is no form-total field in the form - amount field value is used for calculation

**Pull request merged**
